name: deploy-test
on: [push, workflow_dispatch]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: first-massage
        uses: actions/checkout@v3
      - name: to install node
        run: echo "Installing Node.js"
      - name: to install dependencies 
        run: echo "Installing dependencies"
      - name: to run test cases 
        run: echo "Running test cases"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: first-massage
        uses: actions/checkout@v3
      - name: to install node
        run: echo "Installing Node.js"
      - name: to install dependencies 
        run: echo "Installing dependencies"
      - name: to deploy 
        run: echo "Deploying application"
